### ISSUE TITLE
GetByCursorDAO 获取数据时为啥要包含 start？

### ISSUE THREAD

**Issue by drtrang** [PhantomThief/cursor-iterator#3]
### 复现场景

1. Sql
```sql
select * from table where id > :id order by id limit :limit
```

2. Service 代码
```java
CursorIterator.<Long, Table>newGenericBuilder()
                .bufferSize(500)
                .start(0L)
                .cursorExtractor(Table::getId)
                .build((id, limit) -> dao.getAll(id, limit))
                .stream();
```

3. 问题
数据库中有 3000 条数据，查询到的结果为 2995，比实际少了 5 条。

4. 问题跟踪
调试发现除第一次的 limit 为 500 外，之后每次查询的 limit 数量为 501，之后又把返回的数据做了裁剪，去掉集合的第一条数据，所以返回的数据仍为 500 条，问题就出在这里，上述 Sql 里查询条件是 `id > :id`，所以导致裁剪数据的时候把本应返回的数据裁掉了。

5. 结论
修复也很简单，将条件更改为 `id >= :id` 即可，并且在 [PageScroller](https://github.com/PhantomThief/cursor-iterator/blob/master/src/main/java/com/github/phantomthief/util/PageScroller.java#L39) 的注释中也看到了相关内容，但是我不太明白为啥这里要包含 start 并且后续用 `limit + 1` & `subList()` 的方式补救，不包含 start 不是更简单点吗？天舟大神求解惑 🙏

	![image](https://user-images.githubusercontent.com/13851701/40168207-7a728a54-59f5-11e8-9c79-655a8b4171d6.png)

**Comment by PhantomThief** [comment]
@drtrang 嗯，裁掉还是用不包含查询其实大多时候差别不大。不过当时想的是，包含id然后裁掉在定位cursor方面在一些情况下比不包含的要精确一些。不过其实大多数时候差别不大，然后不裁掉的方案在这种时候也许的确会更好一些。

**Comment by drtrang** [comment]
嗯，了解一下当时是的设计理念就好了，在已知的情况下两者没有差别。
准备去听天舟大神讲课了，哈哈 😄
